version: 0.0
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing"
  pre_build: 
    commands:
      - echo Installing source NPM dependencies...
      - npm install -f
  build:
    commands:
      - echo Build started on `date`
      - echo "No build required for this project"
  post_build:
    commands:
      - echo build Completed on `date`
artifacts:
  files:
    - '**/*'
